# Generated by Django 3.2.4 on 2021-06-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_sppd_maksud_perjalanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppd',
            name='jenis_transportasi',
            field=models.CharField(choices=[('Transportasi Laut', 'Laut'), ('Transportasi Darat', 'Darat'), ('Transportasi Udara', 'Udara')], max_length=200, null=True),
        ),
    ]
