# Generated by Django 3.2.4 on 2021-06-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_sppd_jenis_transportasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat_perintah',
            name='pengikut',
            field=models.ManyToManyField(related_name='Surat_perintahs', to='myapp.Pegawai'),
        ),
    ]
