# Generated by Django 3.2.4 on 2021-07-16 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210716_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat_perintah',
            name='koordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='myapp.pegawai'),
        ),
        migrations.AlterField(
            model_name='surat_perintah',
            name='penanggung_jawab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.pegawai'),
        ),
        migrations.AlterField(
            model_name='surat_perintah',
            name='pengikut',
            field=models.ManyToManyField(blank=True, null=True, related_name='Surat_perintahs', to='myapp.Pegawai'),
        ),
    ]
