# Generated by Django 3.2.4 on 2021-07-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210716_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengeluaran',
            name='mobilitas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='pesawat_pergi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pengeluaran',
            name='pesawat_pulang',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='surat_perintah',
            name='pengikut',
            field=models.ManyToManyField(blank=True, related_name='Surat_perintahs', to='myapp.Pegawai'),
        ),
    ]
